# Generated by Django 4.1.7 on 2023-04-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='epub_file',
            field=models.FileField(null=True, upload_to='reader/media/epubs/'),
        ),
    ]
