# Generated by Django 4.1.7 on 2023-04-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_alter_book_epub_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
    ]
