# Generated by Django 4.1.7 on 2023-04-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_ad_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_book',
            name='epub_file_ad',
            field=models.FileField(null=True, upload_to='ad_epub/'),
        ),
    ]
